INSERT INTO TEST_TOTAL_COA (ID, ACCOUNT_ID, ACCOUNT_NAME, GROUP_ID, GROUP_NAME, USER_ID) VALUES (1, 'A001', 'Cash', 'G001', 'Finance', 1);
INSERT INTO TEST_TOTAL_COA (ID, ACCOUNT_ID, ACCOUNT_NAME, GROUP_ID, GROUP_NAME, USER_ID) VALUES (2, 'A002', 'Accounts Receivable', 'G001', 'Finance', 2);

INSERT INTO TEST_TRANSACTION (ID, ACCOUNT_ID, TRANSACTION_AMOUNT, TRANSACTION_DATE) VALUES (1, 'A001', 1000.0, '2023-07-01');
INSERT INTO TEST_TRANSACTION (ID, ACCOUNT_ID, TRANSACTION_AMOUNT, TRANSACTION_DATE) VALUES (2, 'A001', 2000.0, '2023-07-02');
INSERT INTO TEST_TRANSACTION (ID, ACCOUNT_ID, TRANSACTION_AMOUNT, TRANSACTION_DATE) VALUES (3, 'A002', 1500.0, '2023-07-01');

INSERT INTO TEST_USER (USER_ID, USER_NAME, EMAIL) VALUES (1, 'John Doe', 'john.doe@example.com');
INSERT INTO TEST_USER (USER_ID, USER_NAME, EMAIL) VALUES (2, 'Jane Smith', 'jane.smith@example.com');